export const LOADING_STATUS = 'LOADING_STATUS';

export const tab = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  STORE_TMP_FORM_DATA: 'STORE_TMP_FORM_DATA',
  CLEAR_FORM_DATA: 'CLEAR_FORM_DATA',
  RESET_FORM_DATA: 'RESET_FORM_DATA'
};

export const GET_CURRENT_TAB_KEY = 'GET_CURRENT_TAB_KEY';
export const GET_TAB_FORM_DATA = 'GET_TAB_FORM_DATA';
