server:
  port: 9000
    #ssl:
    #key-store: classpath:keystore.p12
    #key-store-password: danit123456
    #keyStoreType: PKCS12
  #keyAlias: tomcat

spring:
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: energym.mail.test@gmail.com
    password:
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
  profiles:
    active: dev

#Global Date format
global:
  date:
    pattern: yyyy-MM-dd
  date-time:
    pattern: yyyy-MM-dd HH-mm-ss

#Application constants
application:
  auth: "/auth"
  authTokenExpTime: 864000000
  authTokenPrefix: "Bearer "
  authHeaderName: Authorization
  secretKey: fs4SecretKey

#Websocket constants
websocket:
  stompEndpoint: "/socket"
  prefix: "/events/"
  postEventEndPoint: "/events/post"
  putEventEndPoint: "/events/put"
  deleteEventEndPoint: "/events/delete"
  getEventEndPoint: "/events/get"

#Avatar image requirements
avatar-image-properties:
  width: 560
  height: 560

#S3 bucket
amazon-properties:
  accessKey:
  secretKey:
  bucketName: energym.data.bucket

