server.port: 9000

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: update
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url: jdbc:mysql://192.168.13.115:3306/danit_final_project?useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: enhancer
spring.datasource.password: 20963520aA
