export const tab = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  LOADING: 'LOADING',
  DONE: 'DONE',
  SET_GRID_DATA: 'SET_GRID_DATA',
  SET_FORM_DATA: 'SET_FORM_DATA',
  STORE_TMP_FORM_DATA: 'STORE_TMP_FORM_DATA',
  CLEAR_FORM_DATA: 'CLEAR_FORM_DATA',
  RESET_FORM_DATA: 'RESET_FORM_DATA'
};

export const GET_CURRENT_TAB_KEY = 'GET_CURRENT_TAB_KEY';
export const GET_TAB_FORM_DATA = 'GET_TAB_FORM_DATA';
