export const tab = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  LOADING_TAB: 'LOADING_TAB',
  DONE_TAB: 'DONE_TAB',
  LOADING_GRID: 'LOADING_GRID',
  DONE_GRID: 'DONE_GRID',
  LOAD_FORM_DATA: 'LOAD_FORM_DATA',
  SET_GRID_DATA: 'SET_GRID_DATA',
  SET_FORM_DATA: 'SET_FORM_DATA',
  CANCEL_EDIT_FORM_DATA: 'CANCEL_EDIT_FORM_DATA',
  STORE_TMP_FORM_DATA: 'STORE_TMP_FORM_DATA',
  SET_FILTER: 'SET_FILTER',
  UPDATE_SORTING: 'UPDATE_SORTING',
  SHOW_EDIT_COLLISION: 'SHOW_EDIT_COLLISION',
  HIDE_EDIT_COLLISION: 'HIDE_EDIT_COLLISION'
};

export const user = {
  UPDATE_AVATAR: 'UPDATE_AVATAR'
};