export const tab = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  LOADING_TAB: 'LOADING_TAB',
  DONE_TAB: 'DONE_TAB',
  LOADING_GRID: 'LOADING_GRID',
  DONE_GRID: 'DONE_GRID',
  SET_GRID_DATA: 'SET_GRID_DATA',
  SET_FORM_DATA: 'SET_FORM_DATA',
  CANCEL_EDIT_FORM_DATA: 'CANCEL_EDIT_FORM_DATA',
  STORE_TMP_FORM_DATA: 'STORE_TMP_FORM_DATA'
};

export const GET_CURRENT_TAB_KEY = 'GET_CURRENT_TAB_KEY';
export const GET_TAB_FORM_DATA = 'GET_TAB_FORM_DATA';
